feat: Add build with artefact upload
Bluebird-Community/bluebird-platform-prototype pull request #1
Opened 2024-06-25 18:49 UTC by indigo423

Created a GitHub actions pipeline with an artifact upload to have something people can play with. The Google Protobuf was hardcoded to OSX x86_64 hardware. I've added a plugin that detects the architecture and allows it to build also on non-OSX systems.

2024-06-25 21:57 UTC, mvrueden requested changes

2024-06-25 21:57 UTC, mvrueden commented on Makefile
> +.DEFAULT_GOAL := compile
-1 on `make`.

The project setup is pretty simple and there is no need for the `make` abstraction.

2024-06-25 21:58 UTC, mvrueden commented
FYI: The protobuf setup is temporarily. I generated the Java files manually without the maven plugin. In general it must be even more dynamic or OpenNMS should expose them properly.

2024-06-25 23:02 UTC, fooker requested changes

2024-06-25 23:02 UTC, fooker commented on Makefile
> +build: clean
```suggestion
build: compile
```

2024-06-27 07:45 UTC, indigo423 commented
> FYI: The protobuf setup is temporarily. I generated the Java files manually without the maven plugin. In general it must be even more dynamic or OpenNMS should expose them properly. Hard-copy them over from OpenNMS source is not the way to go 😱

Thanks for the explanation, but what are the consequences of your explanation to the PR?

2024-07-20 10:23 UTC, closed without merging